[package]
name = "docbox-cli"
version = "0.2.0"
edition = "2024"

license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# Environment variables 
dotenvy = "=0.15.7"

# Command line parser
clap = { version = "=4.5.40", features = ["derive"] }

# Error reporting
eyre = "=0.6.12"
color-eyre = "=0.6.5"

# Core business logic
docbox-core = { version = "0.2.0", path = "../docbox-core" }

# Database access
docbox-database = { version = "0.2.0", path = "../docbox-database" }

# Search access
docbox-search = { version = "0.2.0", path = "../docbox-search" }

docbox-management = { version = "0.1.0", path = "../docbox-management" }

# Asynchronous runtime & Helpers
tokio = { workspace = true, features = ["full"] }
futures.workspace = true

# Serialization and JSON
serde.workspace = true
serde_json.workspace = true

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true

mime.workspace = true
mime_guess.workspace = true

anyhow.workspace = true
thiserror.workspace = true

itertools.workspace = true
