services:
  # Search index
  typesense:
    image: typesense/typesense:28.0
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    environment:
      TYPESENSE_API_KEY: typesensedev     
      TYPESENSE_DATA_DIR: /data

  # Database
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docbox

  # UI for working with local postgres instance
  pgadmin:
    image: dpage/pgadmin4:8.14
    ports:
      - 5433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
    networks:
      - docbox

  # S3 compatible server
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9090:9000" # S3 API
      - "9091:9001" # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://host.docker.internal:8080/webhook/s3"
      MINIO_NOTIFY_WEBHOOK_QUEUE_DIR: "/data/events"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - docbox
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # HTTP proxy server
  squid:
    image: sameersbn/squid:3.5.27-2
    ports:
      - "3128:3128"
    volumes:
      - ./dev.squid.conf:/etc/squid/squid.conf

  # Docbox server
  docbox:
    build:
      context: .
      dockerfile: ./containers/Docbox.Dockerfile
    ports:
      - 8080:8080
    env_file:
      - docker.env
    networks:
      - docbox
    depends_on:
      - database
      - minio
      - opensearch-node1
      - opensearch-node2
      - opensearch-dashboards
      - squid
    profiles: ["api"]

  # Office file converter server
  office-convert-server:
    build:
      context: .
      dockerfile: ./containers/OfficeConvertServer.Dockerfile
    ports:
      - 3000:3000
    networks:
      - docbox
    restart: always

volumes:
  postgres_data:
  pgadmin-data:
  minio-data:
  typesense-data:
  
networks:
  opensearch-net:
  docbox:
    driver: bridge
