# Docker Compose Typesense
#
# This configuration is for a docbox server backend by a typesense search index.
#
# Requires the following environment variables in .env.docker (inside .containers):
# * TYPESENSE_API_KEY
# * RUSTFS_ACCESS_KEY
# * RUSTFS_SECRET_KEY
# * POSTGRES_PASSWORD
# * SM_ENCRYPTION_KEY
# * SM_ACCESS_KEY_ID
# * SM_ACCESS_KEY_SECRET
services:
    # Database
    database:
        image: "postgres:latest"
        container_name: docbox-database
        ports:
            - 8107:5432
        env_file:
            - .env.docker
        environment:
            POSTGRES_USER: docbox
        volumes:
            - docbox-database-data:/var/lib/postgresql/data

    # Search
    search:
        image: typesense/typesense:28.0
        container_name: docbox-search
        ports:
            - 8108:8108
        env_file:
            - .env.docker
        environment:
            TYPESENSE_DATA_DIR: /data
        volumes:
            - docbox-search-data:/data

    # Storage (ARN = arn:rustfs:sqs:us-east-1:primary:webhook)
    storage:
        image: rustfs/rustfs:latest
        container_name: docbox-storage
        ports:
            - 8109:9000
            - 8112:9001
        env_file:
            - .env.docker
        environment:
            RUSTFS_CONSOLE_ENABLE: "true"
            RUSTFS_NOTIFY_ENABLE: "true"
            RUSTFS_NOTIFY_WEBHOOK_ENABLE_PRIMARY: "on"
            RUSTFS_NOTIFY_WEBHOOK_ENDPOINT_PRIMARY: "http://host.docker.internal:8080/webhook/s3"
            RUSTFS_NOTIFY_WEBHOOK_AUTH_TOKEN_PRIMARY: "test"
            RUSTFS_NOTIFY_WEBHOOK_QUEUE_DIR_PRIMARY: "/data/events"
            RUSTFS_OUTBOUND_ALLOW_ORIGINS: "http://host.docker.internal:8080"
        volumes:
            - docbox-storage-data:/data
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # AWS Secrets Manager compatible server (https://github.com/jacobtread/loker)
    secrets:
        image: jacobtread/loker:0.2.3
        container_name: docbox-secrets
        ports:
            - "8110:8080"
        env_file:
            - .env.docker
        environment:
            SM_DATABASE_PATH: /data/secrets.db
        volumes:
            - docbox-secrets-data:/data

    # Office file converter server
    office-convert-server:
        image: jacobtread/office-convert-server:0.2.2
        container_name: docbox-office-converter
        ports:
            - "8111:3000"
        restart: unless-stopped

volumes:
    docbox-database-data:
    docbox-search-data:
    docbox-storage-data:
    docbox-secrets-data:
