ALTER TABLE "docbox_files"
ADD COLUMN "pinned" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "docbox_folders"
ADD COLUMN "pinned" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "docbox_links"
ADD COLUMN "pinned" BOOLEAN NOT NULL DEFAULT FALSE;