[package]
name = "docbox-storage"
version = "0.1.0"
edition = "2024"
description = "Docbox storage layer abstraction"

license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# Database access
docbox-database.workspace = true

# Futures streams
futures.workspace = true

# Error handling
thiserror.workspace = true

# Serialization
serde.workspace = true

# Logging
tracing.workspace = true

# AWS Config
aws-config.workspace = true

# S3 SDK
aws-sdk-s3 = "=1.98.0"

# Not used: Used to enable the "byte-stream-poll-next" feature, used for the storage
# implementation to implement stream
aws-smithy-types = { version = "=1.3.2", features = [
    "byte-stream-poll-next",
    "rt-tokio",
] }

# Bytes
bytes.workspace = true
bytes-utils.workspace = true

# Date time
chrono.workspace = true

[dev-dependencies]
testcontainers = { workspace = true, features = ["http_wait"] }
testcontainers-modules = { workspace = true, features = ["postgres", "minio"] }
tokio = { workspace = true, features = ["full"] }
