[package]
name = "docbox-search"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = []

[dependencies]
# Database access
docbox-database = { version = "0.1.0", path = "../docbox-database" }

# HTTP client
reqwest = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Serialization and JSON
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }

# Logging
tracing = { workspace = true }

# Opensearch client
opensearch = { version = "2.2.0", default-features = false, features = [
    "rustls-tls",
    "aws-auth",
] }

# Validation & Axum validation integration
garde = { workspace = true }

# AWS Config, AWS S3 sdk, AWS typing internals
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }

bytes = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
mime = { workspace = true }

utoipa = { workspace = true }
itertools = "0.14.0"
