[package]
name = "docbox-search"
version = "0.4.0"
edition = "2024"
description = "Docbox multi-backend search abstraction"

license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[features]
default = ["opensearch", "typesense"]
opensearch = ["dep:opensearch"]
typesense = []
database = []

[dependencies]
docbox-database.workspace = true
docbox-secrets.workspace = true

tokio.workspace = true

reqwest.workspace = true

anyhow.workspace = true

serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true

tracing.workspace = true

garde.workspace = true

aws-config.workspace = true

uuid.workspace = true

chrono.workspace = true

mime.workspace = true

utoipa.workspace = true

itertools.workspace = true

# Opensearch client for Opensearch backend
[dependencies.opensearch]
version = "=2.3.0"
default-features = false
optional = true
features = ["rustls-tls", "aws-auth"]
