[package]
name = "docbox-processing"
version = "0.1.0"
edition = "2024"
description = "Docbox file processing logic"

license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# Database types
docbox-database.workspace = true

# Search index types
docbox-search.workspace = true

# PDF to image conversion, text extraction
pdf_process = "=0.2.0"

# Office conversion client
office-convert-client = "=0.5.0"

# Image conversion and manipulation
image = "=0.25.6"

# Email parsing
mail-parser = "=0.11.0"

# HTML parser for email HTML to text
tl.workspace = true

# Escape HTML text
html-escape = "=0.2.13"

# Asynchronous runtime & Helpers
futures.workspace = true
tokio.workspace = true

# HTTP client
reqwest.workspace = true

# Error handling
thiserror.workspace = true

# Serialization and JSON
serde.workspace = true
serde_json.workspace = true

# Logging
tracing.workspace = true

bytes.workspace = true

mime.workspace = true

# Base64 encoding / decoding
base64.workspace = true

utoipa.workspace = true

[dev-dependencies]
testcontainers = { workspace = true, features = ["http_wait"] }
testcontainers-modules = { workspace = true, features = ["postgres", "minio"] }
tokio = { workspace = true, features = ["full"] }
# Enable typesense search backend for testing
docbox-search.workspace = true
mime_guess.workspace = true
