[package]
name = "docbox-core"
version = "0.4.0"
edition = "2024"
description = "Docbox core business logic and functionality"

license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# Database access
docbox-database.workspace = true

# Search access
docbox-search.workspace = true

# File processing
docbox-processing.workspace = true

# Secret management
docbox-secrets.workspace = true

# Storage access
docbox-storage.workspace = true

# Asynchronous runtime & Helpers
tokio = { workspace = true, features = ["full"] }
futures.workspace = true

# Error handling
thiserror.workspace = true

# Serialization and JSON
serde.workspace = true
serde_json.workspace = true

# Logging
tracing.workspace = true

# AWS Config
aws-config.workspace = true
# AWS SQS sdk
aws-sdk-sqs = "=1.76.0"

bytes.workspace = true

itertools.workspace = true

uuid.workspace = true

chrono.workspace = true

mime.workspace = true
mime2ext.workspace = true
mime_guess.workspace = true

# Hashing for file contents
sha256 = { version = "=1.6.0", default-features = false }

utoipa.workspace = true

# Caching
moka.workspace = true

[dev-dependencies]
testcontainers = { workspace = true, features = ["http_wait"] }
testcontainers-modules = { workspace = true, features = ["postgres", "minio"] }
tokio = { workspace = true, features = ["full"] }
# Enable typesense search backend for testing
docbox-search = { workspace = true, features = ["typesense"]}
