[package]
name = "docbox-core"
version = "0.3.1"
edition = "2024"
description = "Docbox core business logic and functionality"

license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# Database access
docbox-database = { version = "0.3.0", path = "../docbox-database" }
docbox-search = { version = "0.3.0", default-features = false, path = "../docbox-search" }

# PDF to image conversion, text extraction 
pdf_process = "=0.2.0"

# Office conversion client
office-convert-client = "=0.5.0"

# Image conversion and manipulation
image = "=0.25.6"

# Asynchronous runtime & Helpers
tokio = { workspace = true, features = ["full"] }
futures.workspace = true

# HTTP client
reqwest.workspace = true

# Error handling
anyhow.workspace = true
thiserror.workspace = true

# Serialization and JSON
serde.workspace = true
serde_json.workspace = true

# Logging
tracing.workspace = true

# AWS Config, AWS S3 sdk, AWS typing internals
aws-config.workspace = true
aws-sdk-s3 = "=1.98.0"
aws-sdk-sqs = "=1.76.0"
aws-sdk-secretsmanager = "=1.80.0"

# Not used: Used to enable the "byte-stream-poll-next" feature, used for the storage 
# implementation to implement stream
aws-smithy-types = { version = "=1.3.2", features = [
    "byte-stream-poll-next",
    "rt-tokio",
] }

# URL encoding to decode object key names
urlencoding = "=2.1.3"

bytes.workspace = true
bytes-utils.workspace = true

itertools.workspace = true

uuid.workspace = true

chrono.workspace = true

mime.workspace = true
mime2ext.workspace = true
mime_guess.workspace = true

sha256 = { version = "=1.6.0", default-features = false }

mail-parser = "=0.11.0"

# Base64 encoding / decoding 
base64.workspace = true

utoipa.workspace = true

# HTML parser for email HTML to text
tl.workspace = true

# Escape HTML text
html-escape = "=0.2.13"

# Caching
moka.workspace = true

# File encryption for JSON file secrets manager
age = "=0.11.1"

[dev-dependencies]
testcontainers = { workspace = true, features = ["http_wait"] }
testcontainers-modules = { workspace = true, features = ["postgres", "minio"] }
tokio = { workspace = true, features = ["full"] }


# Enable typesense search backend for testing
docbox-search = { version = "0.3.0", default-features = false, path = "../docbox-search", features = [
    "typesense",
] }
