[package]
name = "docbox-core"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
# Mock header values, used for browser local testing
mock-browser = []

[dependencies]
# Database access
docbox-database = { version = "0.1.0", path = "../docbox-database" }
docbox-search = { version = "0.1.0", default-features = false, path = "../docbox-search" }

# PDF to image conversion, text extraction 
pdf_process = "0.2.0"

# Office conversion client
office-convert-client = "0.5.0"

# Image conversion and manipulation
image = "=0.25.6"

# Asynchronous runtime & Helpers
tokio = { workspace = true, features = ["full"] }
futures.workspace = true

# HTTP client
reqwest.workspace = true

# Error handling
anyhow.workspace = true
thiserror.workspace = true

# Serialization and JSON
serde.workspace = true
serde_json.workspace = true

# Logging
tracing.workspace = true

# Validation & Axum validation integration
garde.workspace = true

# AWS Config, AWS S3 sdk, AWS typing internals
aws-config.workspace = true
aws-sdk-s3 = { version = "1.91.0", features = [] }
aws-sdk-sqs = { version = "1.72.0", features = [] }
aws-smithy-types = { version = "1.3.2", features = [
    "byte-stream-poll-next",
    "rt-tokio",
] }
aws-sdk-secretsmanager = "1.76.0"

# URL encoding to decode object key names
urlencoding = "=2.1.3"

bytes.workspace = true
bytes-utils.workspace = true

uuid.workspace = true

chrono.workspace = true

mime.workspace = true
mime2ext.workspace = true

# SHA256 Hashing
sha256 = { version = "=1.6.0", default-features = false }

mail-parser = "=0.11.0"

# Base64 encoding / decoding 
base64.workspace = true


utoipa.workspace = true
itertools.workspace = true

# HTML parser for email HTML to text
tl.workspace = true
# Escape HTML text
html-escape = "=0.2.13"
# Caching
moka.workspace = true
age = "=0.11.1"

[dev-dependencies]
testcontainers = { version = "0.24.0", features = ["http_wait"] }
testcontainers-modules = { version = "0.12.1", features = [
    "postgres",
    "minio",
] }
tokio = { workspace = true, features = ["full"] }
mime_guess.workspace = true

# Enable typesense search backend for testing
docbox-search = { version = "0.1.0", default-features = false, path = "../docbox-search", features = [
    "typesense",
] }
